apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sandbox.fullname" . }}-bridge
  labels:
    {{- include "sandbox.labels" . | nindent 4 }}
data:
  __init__.py: |
{{ .Files.Get "files/sandbox/__init__.py" | nindent 4 }}
  bridge.py: |
{{ .Files.Get "files/sandbox/bridge.py" | nindent 4 }}
  log_config.py: |
{{ .Files.Get "files/sandbox/log_config.py" | nindent 4 }}
  types.py: |
{{ .Files.Get "files/sandbox/types.py" | nindent 4 }}
  proxy.mjs: |
{{ .Files.Get "files/sandbox/proxy.mjs" | nindent 4 }}
  entrypoint.py: |
{{ .Files.Get "files/sandbox/entrypoint.py" | nindent 4 }}
