apiVersion: v1
kind: Service
metadata:
  name: {{ include "sandbox.fullname" . }}
  labels:
    {{- include "sandbox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sandbox.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.sandboxImage.proxyPort }}
      targetPort: proxy
    - name: opencode
      port: {{ .Values.sandboxImage.opencodePort }}
      targetPort: opencode
    - name: terminal
      port: {{ .Values.ttyd.port }}
      targetPort: ttyd
    - name: browser
      port: {{ .Values.browser.port }}
      targetPort: browser
